name: Terraform Apply

on:
  workflow_dispatch:  # Allows manual triggering
    inputs:
      environment:
        description: 'Environment to apply for (dev or prod)'
        required: true
        default: dev

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.SANDBOX2_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SANDBOX2_AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Set environment
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment || 'dev' }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init -backend-config="./environment/${{ env.ENVIRONMENT }}/backend-${{ env.ENVIRONMENT }}.tfvars"

      - name: Terraform Apply
        run: terraform apply -var-file="./environment/${{ env.ENVIRONMENT }}/${{ env.ENVIRONMENT }}.tfvars" -auto-approve